- app.ts
- database/models/student.model.ts
- database/models/teacher.model.ts
- database/models/user.model.ts
- package.json
- routes/apiController.ts
- routes/controllers/dev.controller.ts
- routes/controllers/verify.controller.ts
- routes/middlewares/common/checkValidation.ts
- routes/middlewares/error/errorMiddleware.ts
- routes/middlewares/error/errorNames.ts
- routes/middlewares/verify/common/passwordEncryption.ts
- routes/middlewares/verify/common/userExistCheck.ts
- routes/middlewares/verify/jwt/issueToken.ts
- routes/middlewares/verify/jwt/veirfyToken.ts
- routes/middlewares/verify/login/_validation.ts
- routes/middlewares/verify/login/login.ts
- routes/middlewares/verify/register/_validation.ts
- routes/middlewares/verify/register/register.ts
- routes/middlewares/verify/register/signKeyCheck.ts
- swagger.json
-  각 유효성 검사 미들웨어이며 express-validator 모듈을 통해 구현
- express-validator 모듈로 유효성 검사가 완료되고 문제가 없었는지 판단해주는 미들웨어
- 요청 id나 signKey가 데이터베이스에 존재하는지 확인하고 각 경로에 따라 처리
- 요청 password를 암호화하여 res.locals.temp에 저장
- 데이터베이스에서 대조나 삽입을 위해 구현
- 비밀번호 대조나 User 모델 업데이트
- res.locals에 존재하는 user 객체와 함께 access token을 응답하는 미들웨어
- 토큰 검증할 미들웨어
> register, login 구현

- README.md
- swagger.json
config/encryption.json
- 비밀번호 암호화할 때 참고하는 설정 json
> docs: README.md 파일 업데이트 및 API 문서 업데이트

- Dockerfile
- Jenkinsfile
**Dockerfile**
- node version 10.15.3 image 다운
- WORKDIR 설정
- npm install 후 npm run start
**Jenkinsfile**
- git repo clone 작업
- 이미지 빌드
- dockerhub로 이미지 push(build_number, latest)
- docker 이미지 삭제
> feat: Dockerfile, Jenkinsfile 추가

- database/index.ts
- database/models/calendar.model.ts
- database/models/meal.model.ts
- database/models/mealOrder.model.ts
- database/models/notice.model.ts
- database/models/noticeLog.model.ts
- database/models/teacher.model.ts
- database/models/timeTable.model.ts
- database/models/user.model.ts
- routes/apiController.ts
- routes/controllers/calendar.controller.ts
- routes/controllers/meal.controller.ts
- routes/controllers/notice.controller.ts
- routes/controllers/timetable.controller.ts
- routes/middlewares/calendar/_validation.ts
- routes/middlewares/calendar/getCalendar.ts
- routes/middlewares/error/errorNames.ts
- routes/middlewares/error/errors.ts
- routes/middlewares/meal/get/_validation.ts
- routes/middlewares/meal/get/getMeal.ts
- routes/middlewares/meal/order/getMealOrder.ts
- routes/middlewares/notice/_validation.ts
- routes/middlewares/notice/createNoticeLog.ts
- routes/middlewares/notice/getNotice.ts
- routes/middlewares/timetable/getTimeTable.ts
- routes/middlewares/user/jwt/getUserFromToken.ts
- routes/middlewares/user/login/_validation.ts
- swagger.json
**student, teacher .model.ts**
- User가 삭제되었을 때, Teacher나 Student도 함께 사라져야하므로 onDelete가 'SET NULL' -> 'CASCADE'로 변경
**calendar, meal, mealOrder, notice, noticeLog, timeTable .model.ts**
- 기능들은 위한 새로운 모델
**getCalendar.ts**
- 기본적으로 요청 달의 일정을 제공
**getMeal.ts**
- 만약 Request sort가 week일 때, 오늘부터 7일 뒤까지의 급식표를 제공하고 아니라면 이번 달의 급식표를 제공
**getMealOrder.ts**
- 항상 MealOrder의 첫 번째 row를 응답값으로 줌
**getNotice.ts**
- 요청된 type에 따라 post나 list형식으로 res.locals.notice에 담음
**createNoticeLog.ts**
- 공지사항 post를 요청했다면 NoticeLog를 findOrCreate함
**getTimeTable.ts**
- 유저의 전공, 학년, 반의 시간표를 조회하여 정렬해서 응답값으로 줌
**getUserFromToken.ts**
- 토큰에서 디코딩된 기본키를 이용하여 유저를 조회한 후 다른 미들웨어에서 사용하기 위해 res.locals.user에 담음
> feat: 공지사항, 급식, 급식순서, 시간표 기능 구현 및 model cascade 수정

- database/models/mealOrder.model.ts
- swagger.json
**mealOrder.model.ts**
- default 값 0->1로 수정
- timetable, calendar, notice, meal api documentation
> docs: timetable, calendar, notice, meal api

- routes/middlewares/board/comment/get/getComment.ts
- routes/middlewares/board/comment/post/postComment.ts
- swagger.json
**getComment.ts, postComment.ts**
- Find board first. But if it doesn't exist, error code will be 404
- Documentation
> docs: board API Documentation

- database/models/board.model.ts
- database/models/boardCommentLike.model.ts
- database/models/boardLike.model.ts
- database/models/user.model.ts
- routes/controllers/board.controller.ts
- routes/middlewares/board/comment/get/getComment.ts
- routes/middlewares/board/get/getBoard.ts
- routes/middlewares/board/like/_validation.ts
- routes/middlewares/board/like/boardLike.ts
- swagger.json
- Documentation
**(board, boardComment, user) .model.ts**
- Association for new feature
**(getBoard, getComment) .ts**
- Show whether user liked board or comment and comment rows count
**(boardLike, boardCommentLike) .model.ts**
- Models for new feature
**boardLike.ts**
- Create BoardLike or BoardCommentLike row If user liked already, that will be destroy
> feat:(board, boardComment) Like

- database/models/calendar.model.ts
- routes/controllers/calendar.controller.ts
- routes/middlewares/calendar/_validation.ts
- routes/middlewares/calendar/get/_validation.ts
- routes/middlewares/calendar/get/getCalendar.ts
- swagger.json
**getCalendar.ts, calendar.model.ts**
- Add year column and apply
- Documentation
> fixed: Add year column in Calendar model

- routes/controllers/calendar.controller.ts
- routes/middlewares/calendar/recent/recentCalendar.ts
**recentCalendar.ts**
- Use operator and order to get recent calendar
> feat: get recent calendar

- routes/middlewares/meal/get/_validation.ts
- routes/middlewares/meal/get/getMeal.ts
- swagger.json
**getMeal.ts**
- (sort === week) Make an array which is 7 length and fill meal
- (sort === week) If it is weekend, detail is '주말'
- (sort === week) If there isn't meal, detail is 'X'
> Get a week of meel

- routes/middlewares/meal/get/getMeal.ts
- routes/middlewares/user/register/signKeyCheck.ts
**getMeal.ts**
- In weekend, they can have meal. So I decided to change procedure.
**signKeyCheck.ts**
- If an user select from User.signkey with lowercase, they give user results with uppercase
> fixed: detect signKey uppercase & change getMeal procedure

- routes/middlewares/user/exist/exist.ts
**exist.ts**
- Check whether requested value equals user[key]
> fixed: exist API check whether requested value equals user[key]

- routes/middlewares/user/exist/_validation.ts
- routes/middlewares/user/exist/exist.ts
**exist.ts**
- never return null
**_validation.ts**
- don't check tp
> Prevent leaking users' phone numbers

- config/.gitignore
- lib/s3.ts
- routes/middlewares/user/common/passwordEncryption.ts
- routes/middlewares/user/phone/fbCheckCode.ts
**passwordEncryption.ts, fbCheckCode.ts**
- Delete import syntax
**fbCheckCode.ts**
- Fix typo
> fixed: Fix typo & delete dotenv in middlewares

- lib/s3.ts
- routes/middlewares/notice/createNoticeLog.ts
**createNoticeLog.ts**
- Add noticeCount key for pagination in GET /notice API
> fixed: add noticeCount for notice pagination

- routes/middlewares/notice/createNoticeLog.ts
- routes/middlewares/notice/getNotice.ts
Fixed bug that we can get only all notice count
> fixed: For title search result count

- swagger.json
- 어드민 페이지 api 문서화
- ???Response 스키마 -> Response 지움. ( ex: MealResponse -> Meal )
- description 수정
- status code 수정
- response 해주는 schema 수정
> admin API 문서화

- routes/middlewares/notice/getNotice.ts
getNotice.ts 404 Error Handling
> fixed: add notice 404 error

- routes/middlewares/board/comment/get/getComment.ts
- routes/middlewares/board/get/getBoard.ts
**getComment.ts, getBoard.ts**
- add resultCount attribute for pagination and infinite scrolling
> fixed: add Board and Comment Count for pagination

- swagger.json
- GET /board, /board/comment Response 값 수정
> swagger 문서 수정

- routes/apiController.ts
> fixed: get status bug

- app.ts
- lib/s3.ts
- routes/apiController.ts
- routes/controllers/board.controller.ts
- routes/controllers/dev.controller.ts
- routes/middlewares/board/like/_validation.ts
- routes/middlewares/board/like/boardLike.ts
- routes/middlewares/common/getStatus.ts
- routes/middlewares/user/common/passwordEncryption.ts
- routes/middlewares/user/jwt/issueToken.ts
- routes/middlewares/user/jwt/veirfyToken.ts
- routes/middlewares/user/phone/fbCheckCode.ts
* GET /like API to POST & allow other types
* Dotenv bug
> GET /like API to POST & allow other types & fixed dotenv bug

- app.ts
- database/models/board.model.ts
- database/models/boardComment.model.ts
- routes/middlewares/board/get/getBoard.ts
- routes/middlewares/board/report/_validation.ts
- routes/middlewares/board/report/report.ts
- routes/middlewares/user/jwt/verifyToken.ts
* Board objects soft delete to hard delete
* report query to body
* cors
> DELETE /board soft delete to hard delete

- routes/controllers/user.controller.ts
- routes/middlewares/user/get/getUser.ts
- routes/middlewares/user/jwt/issueToken.ts
- routes/middlewares/user/patch/phone/_validation.ts
- routes/middlewares/user/phone/phoneInsert.ts
- swagger.json
> PATCH /user/phone Feature

- README.md
- routes/middlewares/board/post/boardMulter.ts
- routes/middlewares/user/jwt/issueToken.ts
- routes/middlewares/user/jwt/verifyToken.ts
* refresh token structure
* POST /board file size limit updated to 5mb
> feat: ready for refresh token

- routes/middlewares/calendar/get/getCalendar.ts
**getCalendar.ts**
* calendar ASC sort by date
> feat: calendar ASC sort by date

- Dockerfile
Dockerfile
- running command for timezone setting
> Dockerfile modify for timezone set

- routes/middlewares/board/comment/get/getComment.ts
- routes/middlewares/board/get/getBoard.ts
> fixed: getComment gets wrong comment count

- database/models/board.model.ts
- database/models/boardComment.model.ts
- routes/adminController.ts
- routes/middlewares/admin/notice/get/_validation.ts
- routes/middlewares/admin/notice/get/getNotice.ts
- routes/middlewares/board/comment/post/postComment.ts
- routes/middlewares/board/post/_validation.ts
- routes/middlewares/board/post/postBoard.ts
**board.model.ts, boardComment.model.ts**
- can update user_name to null value
**postBoard.ts, postComment.ts**
- set user_name null if anonymous property is true
> Board Anonymous Feature

- database/models/user.model.ts
- package.json
- routes/controllers/user.controller.ts
- routes/middlewares/user/get/getUser.ts
- routes/middlewares/user/image/post/imageMulter.ts
- routes/middlewares/user/image/post/postImage.ts
- routes/middlewares/user/image/post/updateImage.ts
- routes/middlewares/user/jwt/issueToken.ts
> feat: POST /user/image

- routes/middlewares/user/jwt/getUserFromToken.ts
**getUserFromToken.ts**
- Add Auto-logout when user info is changed
> Auto-logout when user info is changed

- database/models/LOLTeam.model.ts
- database/models/LOLTeamMember.model.ts
- database/models/LOLVote.model.ts
- database/models/match.model.ts
- database/models/singer.model.ts
- database/models/user.model.ts
- routes/apiController.ts
- routes/controllers/festival.controller.ts
- routes/controllers/festival/admin.controller.ts
- routes/controllers/festival/event.controller.ts
- routes/controllers/festival/lol.controller.ts
- routes/controllers/festival/timetable.controller.ts
- routes/middlewares/festival/admin/FSUserCheck.ts
- routes/middlewares/festival/admin/_validation.ts
- routes/middlewares/festival/lol/get/getLOLTeam.ts
- routes/middlewares/festival/lol/post/_validation.ts
- routes/middlewares/festival/lol/post/postLOLVote.ts
- routes/middlewares/festival/match/get/getMatch.ts
- routes/middlewares/festival/singer/get/getSinger.ts
- routes/middlewares/festival/singer/post/_validation.ts
- routes/middlewares/festival/singer/post/postSingerVote.ts
- routes/middlewares/festival/timetable/getfsTimeTable.ts
- tslint.json
**festival.controller.ts**
- 축제 기능 라우터 연결
**getLol.ts**
- 한챔스 결승전 대진표 API
**postLolVote.ts**
- 한챔스 결승전 승부예측 투표 API
**getMatch.ts**
- 한마당 짝 찾기 이벤트 번호 확인 API
**getSinger.ts**
- 복면가왕 참가자 목록 API
**postSingerVote.ts**
- 복면가왕 투표 API
**getFestivalTimeTable.ts**
- 한마당 타임테이블 API
> Festival Event API feature

- app.ts
> db connect logging true

- routes/controllers/festival/lol.controller.ts
> fixed: change directory name

- routes/controllers/festival/timetable.controller.ts
- change lowercase to uppercase 'FS'
> fixed: change lowercase to uppercase 'FS'

- swagger.json
> feat: Add recruit api
